(() => {
'use strict';
const K={setup:'cr3atix-vigilance-setup-v19',cal:'cr3atix-vigilance-eye-calibration-v1',vol:'cr3atix-vigilance-alarm-volume-v1',det:'cr3atix-vigilance-detection-settings-v172'};
const SCHEMA=2;
const $=s=>document.querySelector(s);let promptEvent=null,timer=null;
const runId=()=>globalThis.crypto?.randomUUID?.()||`setup-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const blankRun=(reason='initial')=>({id:runId(),reason,startedAt:new Date().toISOString(),calibrationConfirmed:false,detectionConfirmed:false,volumeConfirmed:false,voiceConfirmed:false,finishedAt:null});
const fresh=()=>({version:19,schema:SCHEMA,completed:false,stage:'install',installDone:false,installSkipped:false,completedAt:null,run:null});
function load(){try{return {...fresh(),...(JSON.parse(localStorage.getItem(K.setup)||'null')||{})}}catch{return fresh()}}
function save(p){const v={...load(),...p,version:19,schema:SCHEMA,lastCheckedAt:new Date().toISOString()};localStorage.setItem(K.setup,JSON.stringify(v));return v}
function installed(){try{return window.matchMedia?.('(display-mode: standalone)').matches===true||window.matchMedia?.('(display-mode: fullscreen)').matches===true||navigator.standalone===true}catch{return false}}
function calData(){try{return JSON.parse(localStorage.getItem(K.cal)||'null')}catch{return null}}
function calOK(){const v=calData();return !!(v&&Number.isFinite(+v.threshold)&&Number.isFinite(+v.baseline))}
function volOK(){const r=localStorage.getItem(K.vol),v=+r;return r!==null&&Number.isFinite(v)&&v>=0&&v<=1}
function detOK(){try{const v=JSON.parse(localStorage.getItem(K.det)||'null');return !!(v&&Number.isFinite(+v.closureDelay)&&+v.closureDelay>=.6&&+v.closureDelay<=3&&Number.isFinite(+v.yawnThreshold)&&+v.yawnThreshold>=.35&&+v.yawnThreshold<=.85&&['siren','voice','both'].includes(v.alarmMode))}catch{return false}}
function configOK(){return calOK()&&volOK()&&detOK()}
function installOK(s=load()){return installed()||s.installSkipped===true}
function ready(s=load()){return s.completed===true&&installOK(s)&&configOK()}
function mode(){return $('input[name="alarmMode"]:checked')?.value||'siren'}
function voiceNow(){return !!($('#listenBtn')&&!$('#listenBtn').disabled)}
function activeRun(s=load()){return s.run&&typeof s.run==='object'&&!s.run.finishedAt?s.run:null}
function startRun(reason='initial',stage=installed()?'settings':'install',extra={}){return save({completed:false,completedAt:null,stage,run:blankRun(reason),...extra})}
function patchRun(p){const s=load(),r=activeRun(s)||blankRun('recovered');return save({run:{...r,...p}})}
function setupCalOK(s=load()){return calOK()&&activeRun(s)?.calibrationConfirmed===true}
function setupDetOK(s=load()){return detOK()&&activeRun(s)?.detectionConfirmed===true}
function setupVolOK(s=load()){return volOK()&&activeRun(s)?.volumeConfirmed===true}
function setupConfigOK(s=load()){return setupCalOK(s)&&setupDetOK(s)&&setupVolOK(s)}
function persistCurrent(){const v=$('#alarmVolume'),c=$('#closureDelay'),y=$('#yawnThreshold');if(v){localStorage.setItem(K.vol,String(Math.max(0,Math.min(100,+v.value||0))/100));v.dispatchEvent(new Event('input',{bubbles:true}))}if(c&&y){localStorage.setItem(K.det,JSON.stringify({closureDelay:+c.value,yawnThreshold:+y.value,alarmMode:mode()}));c.dispatchEvent(new Event('input',{bubbles:true}));y.dispatchEvent(new Event('input',{bubbles:true}))}}
function overlay(){let o=$('#firstRunOverlay');if(!o){o=document.createElement('div');o.id='firstRunOverlay';o.className='first-run-overlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');o.innerHTML='<div class="first-run-card" id="firstRunCard"></div>';document.body.appendChild(o)}return o}
function show(on=true){overlay().classList.toggle('show',on);document.documentElement.classList.toggle('setup-open',on)}
const dots=n=>`<div class="setup-progress"><span class="${n>=1?'active':''}">1</span><i></i><span class="${n>=2?'active':''}">2</span><i></i><span class="${n>=3?'active':''}">3</span></div>`;
function checks(){const s=load(),m=mode(),voice=voiceNow(),c=setupCalOK(s),d=setupDetOK(s),v=setupVolOK(s);return `<div class="setup-checklist"><div class="${c?'done':''}"><span>${c?'✓':'1'}</span><p><b>Caméra calibrée</b><small>${c?'Calibration effectuée pendant cette configuration.':'Lance la calibration des yeux pendant 3 secondes, même si une ancienne valeur existe.'}</small></p></div><div class="${d?'done':''}"><span>${d?'✓':'2'}</span><p><b>Détection confirmée</b><small>${d?'Seuils confirmés pendant cette configuration.':'Régle ou confirme la fermeture des yeux et la sensibilité du bâillement.'}</small></p></div><div class="${v?'done':''}"><span>${v?'✓':'3'}</span><p><b>Volume confirmé</b><small>${v?'Volume confirmé pendant cette configuration.':'Choisis ou confirme un niveau d’alarme audible.'}</small></p></div><div class="optional ${voice?'done':''}"><span>${voice?'✓':'○'}</span><p><b>Voix personnelle · facultatif</b><small>${m==='siren'?'La sirène est sélectionnée.':voice?'Message vocal prêt pour cette session.':'Enregistre puis écoute ton message si tu utilises le mode voix.'}</small></p></div></div>`}
function installStep(msg=''){let s=load();if(!activeRun(s))s=startRun(s.completed?'reinstall':'initial','install',{installDone:s.installDone,installSkipped:false});const ok=installed();show();$('#firstRunCard').innerHTML=`${dots(1)}<div class="setup-kicker">PREMIÈRE MISE EN ROUTE</div><h2 id="firstRunTitle">Préparons VIGILANCE</h2><p class="setup-lead">L’installation et quelques réglages essentiels permettent un démarrage fiable avant le premier trajet.</p><div class="setup-focus ${ok?'ok':''}"><span class="setup-focus-icon">${ok?'✓':'↓'}</span><div><b>${ok?'Application installée':'Installer l’application'}</b><small>${ok?'VIGILANCE fonctionne actuellement en mode application.':s.installDone?'Une ancienne installation est mémorisée, mais elle n’est plus détectée. Réinstalle VIGILANCE.':'Installation recommandée pour un accès rapide depuis le téléphone.'}</small></div></div>${msg?`<div class="setup-message">${msg}</div>`:''}<div class="setup-actions"><button id="setupInstallAction" class="setup-primary">${ok?'CONTINUER':promptEvent?'INSTALLER VIGILANCE':'VÉRIFIER L’INSTALLATION'}</button>${!ok&&!promptEvent?'<button id="setupInstallSkip" class="setup-secondary">CONFIGURER MAINTENANT</button>':''}</div>${!ok&&!promptEvent?'<p class="setup-help">Si Chrome ne propose pas encore l’installation, utilise le menu ⋮ puis « Installer l’application » ou « Ajouter à l’écran d’accueil ».</p>':''}`;
$('#setupInstallAction').onclick=async()=>{if(installed()){save({installDone:true,installSkipped:false,stage:'settings'});settingsStep();return}if(promptEvent){try{await promptEvent.prompt();const r=await promptEvent.userChoice;if(r?.outcome==='accepted'){save({installDone:true,installSkipped:false,stage:'settings'});promptEvent=null;settingsStep('Installation validée. Passons aux réglages.')}else installStep('Installation annulée. Tu peux la relancer quand tu veux.')}catch{installStep('La fenêtre automatique n’est pas disponible. Utilise le menu du navigateur.')}}else installStep('L’application n’est pas détectée comme installée pour le moment.')};
$('#setupInstallSkip')?.addEventListener('click',()=>{save({installSkipped:true,stage:'settings'});settingsStep('Tu peux terminer les réglages maintenant et installer l’application ensuite.')})}
function settingsStep(msg=''){let s=load();if(!activeRun(s))s=startRun('configuration',installed()?'settings':s.installSkipped?'settings':'install',{installDone:s.installDone,installSkipped:s.installSkipped});save({stage:'settings',installDone:installed()||s.installDone});show();$('#firstRunCard').innerHTML=`${dots(2)}<div class="setup-kicker">CONFIGURATION ESSENTIELLE</div><h2 id="firstRunTitle">Réglons VIGILANCE</h2><p class="setup-lead">Pour cette mise en route, calibre réellement la caméra puis confirme la détection et le volume. Les anciennes valeurs ne valident plus automatiquement les étapes.</p>${msg?`<div class="setup-message ok">${msg}</div>`:''}${checks()}<div class="setup-actions"><button id="setupOpenSettings" class="setup-primary">OUVRIR LES PARAMÈTRES</button><button id="setupCheckNow" class="setup-secondary">VÉRIFIER MAINTENANT</button></div>`;$('#setupOpenSettings').onclick=openSettings;$('#setupCheckNow').onclick=()=>setupConfigOK()?verifyStep():settingsStep('Il reste au moins un réglage obligatoire à effectuer ou confirmer pendant cette configuration.')}
function dock(){let d=$('#setupDock');if(!d){d=document.createElement('aside');d.id='setupDock';d.className='setup-dock';document.body.appendChild(d)}const ok=setupConfigOK();d.innerHTML=`<div class="setup-dock-head"><div><small>PREMIÈRE CONFIGURATION</small><b>${ok?'Réglages essentiels prêts':'Termine les réglages essentiels'}</b></div><span>${ok?'✓':'…'}</span></div>${checks()}<div class="setup-dock-actions"><button id="setupSaveCurrent" class="setup-secondary">CONFIRMER DÉTECTION ET VOLUME</button><button id="setupFinishSettings" class="setup-primary" ${ok?'':'disabled'}>TERMINER LA CONFIGURATION</button></div>`;d.classList.add('show');$('#setupSaveCurrent').onclick=()=>{persistCurrent();patchRun({detectionConfirmed:detOK(),volumeConfirmed:volOK()});dock();statusPanel()};$('#setupFinishSettings').onclick=()=>{if(setupConfigOK()){d.classList.remove('show');verifyStep()}else dock()};return d}
function openSettings(){show(false);$('#settingsBtn')?.click();dock();clearInterval(timer);timer=setInterval(()=>{if(!load().completed&&!$('#settingsView')?.hidden)dock();else clearInterval(timer)},1500)}
function verifyStep(){if(!setupConfigOK()){settingsStep('La vérification a détecté un réglage non confirmé pendant cette configuration.');return}const s=load();show();$('#firstRunCard').innerHTML=`${dots(3)}<div class="setup-kicker">VÉRIFICATION FINALE</div><h2 id="firstRunTitle">VIGILANCE est prête</h2><p class="setup-lead">Les réglages essentiels viennent d’être confirmés sur cet appareil. Aux prochains démarrages, l’accueil s’ouvrira directement tant que la configuration reste valide.</p><div class="setup-summary"><div><span>Installation</span><b>${installed()?'✓ Installée':s.installSkipped?'◌ Navigateur':'À installer'}</b></div><div><span>Caméra</span><b>✓ Calibrée maintenant</b></div><div><span>Détection</span><b>✓ Confirmée</b></div><div><span>Volume</span><b>✓ ${Math.round(+localStorage.getItem(K.vol)*100)} %</b></div></div><div class="setup-actions"><button id="setupComplete" class="setup-primary">ACCÉDER À L’ACCUEIL</button></div><p class="setup-help">Avant chaque trajet, garde le téléphone correctement positionné face au conducteur. VIGILANCE reste une aide et ne remplace jamais le repos.</p>`;$('#setupComplete').onclick=()=>{const now=new Date().toISOString(),r=activeRun(s);save({completed:true,stage:'done',installDone:installed()||s.installDone,completedAt:now,run:r?{...r,finishedAt:now}:null});$('#setupDock')?.classList.remove('show');show(false);$('#backBtn')?.click();statusPanel()}}
function injectPanel(){if($('#setupSystemPanel'))return;const host=$('.settings-sections');if(!host)return;const sec=document.createElement('section');sec.id='setupSystemPanel';sec.className='settings-section glass wide-section setup-system-panel';host.appendChild(sec);statusPanel()}
function statusPanel(){const sec=$('#setupSystemPanel');if(!sec)return;const s=load(),ok=ready(s),currentInstall=installed();sec.innerHTML=`<div class="section-heading"><span class="section-icon">✓</span><div><span class="eyebrow">MISE EN ROUTE</span><h3>État de configuration</h3></div></div><div class="setup-status-grid"><div><span>Application</span><b>${currentInstall?'✓ Installée':s.installSkipped?'◌ Navigateur':s.installDone?'⚠ Ancienne installation':'À installer'}</b></div><div><span>Caméra</span><b>${calOK()?'✓ Calibration enregistrée':'À calibrer'}</b></div><div><span>Détection</span><b>${detOK()?'✓ Réglages enregistrés':'À régler'}</b></div><div><span>Volume</span><b>${volOK()?`✓ ${Math.round(+localStorage.getItem(K.vol)*100)} %`:'À confirmer'}</b></div></div><div class="setup-system-state ${ok?'ok':'warn'}">${ok?'✓ VIGILANCE EST PRÊTE À FONCTIONNER':'⚠ CONFIGURATION À TERMINER'}</div><button id="restartSetupBtn" class="btn secondary">REFAIRE LA CONFIGURATION INITIALE</button>`;$('#restartSetupBtn').onclick=()=>{startRun('manual',installed()?'settings':'install',{installDone:s.installDone,installSkipped:false});installed()?settingsStep('Nouvelle configuration démarrée : les étapes doivent être confirmées à nouveau.'):installStep('Nouvelle configuration démarrée.')};}
function migrate(){const s=load();if(s.schema===SCHEMA)return s;if(s.completed&&configOK()){return save({schema:SCHEMA,run:null})}return startRun('migration',installed()?'settings':'install',{installDone:s.installDone,installSkipped:false})}
function boot(){injectPanel();let s=migrate();if(installed()&&!s.installDone)s=save({installDone:true});if(ready(s)){show(false);statusPanel();return}if(s.completed&&!installOK(s)){s=startRun('reinstall','install',{installDone:s.installDone,installSkipped:false})}else if(s.completed&&!configOK()){const r=blankRun('repair');r.calibrationConfirmed=calOK();r.detectionConfirmed=detOK();r.volumeConfirmed=volOK();s=save({completed:false,completedAt:null,stage:'settings',run:r})}else if(!activeRun(s)){s=startRun('initial',installOK(s)?'settings':'install',{installDone:s.installDone,installSkipped:s.installSkipped})}if(!installOK(s)&&s.stage==='install')installStep();else settingsStep()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;if(!load().completed&&load().stage==='install')installStep()});
window.addEventListener('appinstalled',()=>{promptEvent=null;const s=load();save({installDone:true,installSkipped:false,stage:'settings'});if(!s.completed)settingsStep('Installation terminée avec succès. Les réglages doivent maintenant être confirmés.');statusPanel()});
document.addEventListener('input',e=>{if(load().completed)return;const t=e.target;if(t?.matches?.('#alarmVolume'))patchRun({volumeConfirmed:volOK()});if(t?.matches?.('#closureDelay,#yawnThreshold,input[name="alarmMode"]'))patchRun({detectionConfirmed:detOK()});if(t?.matches?.('#alarmVolume,#closureDelay,#yawnThreshold,input[name="alarmMode"]'))setTimeout(()=>{$('#setupDock')?.classList.contains('show')&&dock();statusPanel()},30)});
$('#calibrateBtn')?.addEventListener('click',()=>{if(load().completed)return;const before=localStorage.getItem(K.cal);const w=setInterval(()=>{const after=localStorage.getItem(K.cal);if(after!==before&&calOK()){clearInterval(w);patchRun({calibrationConfirmed:true});$('#setupDock')?.classList.contains('show')&&dock();statusPanel()}},400);setTimeout(()=>clearInterval(w),18000)});
$('#recordBtn')?.addEventListener('click',()=>setTimeout(()=>{if(!load().completed&&voiceNow())patchRun({voiceConfirmed:true});$('#setupDock')?.classList.contains('show')&&dock()},5600));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();