(() => {
'use strict';
const K={setup:'cr3atix-vigilance-setup-v19',cal:'cr3atix-vigilance-eye-calibration-v1',vol:'cr3atix-vigilance-alarm-volume-v1',det:'cr3atix-vigilance-detection-settings-v172'};
const $=s=>document.querySelector(s);let promptEvent=null,timer=null;
const fresh=()=>({version:19,completed:false,stage:'install',installDone:false,installSkipped:false,completedAt:null});
function load(){try{return {...fresh(),...(JSON.parse(localStorage.getItem(K.setup)||'null')||{})}}catch{return fresh()}}
function save(p){const v={...load(),...p,version:19,lastCheckedAt:new Date().toISOString()};localStorage.setItem(K.setup,JSON.stringify(v));return v}
function installed(){return matchMedia?.('(display-mode: standalone)').matches===true||matchMedia?.('(display-mode: fullscreen)').matches===true||navigator.standalone===true}
function calOK(){try{const v=JSON.parse(localStorage.getItem(K.cal)||'null');return !!(v&&Number.isFinite(+v.threshold)&&Number.isFinite(+v.baseline))}catch{return false}}
function volOK(){const r=localStorage.getItem(K.vol),v=+r;return r!==null&&Number.isFinite(v)&&v>=0&&v<=1}
function detOK(){try{const v=JSON.parse(localStorage.getItem(K.det)||'null');return !!(v&&Number.isFinite(+v.closureDelay)&&+v.closureDelay>=.6&&+v.closureDelay<=3&&Number.isFinite(+v.yawnThreshold)&&+v.yawnThreshold>=.35&&+v.yawnThreshold<=.85&&['siren','voice','both'].includes(v.alarmMode))}catch{return false}}
function configOK(){return calOK()&&volOK()&&detOK()}
function installOK(s=load()){return installed()||s.installDone||s.installSkipped}
function ready(s=load()){return s.completed&&installOK(s)&&configOK()}
function mode(){return $('input[name="alarmMode"]:checked')?.value||'siren'}
function voiceNow(){return !!($('#listenBtn')&&!$('#listenBtn').disabled)}
function persistCurrent(){const v=$('#alarmVolume'),c=$('#closureDelay'),y=$('#yawnThreshold');if(v){localStorage.setItem(K.vol,String(Math.max(0,Math.min(100,+v.value||0))/100));v.dispatchEvent(new Event('input',{bubbles:true}))}if(c&&y){localStorage.setItem(K.det,JSON.stringify({closureDelay:+c.value,yawnThreshold:+y.value,alarmMode:mode()}));c.dispatchEvent(new Event('input',{bubbles:true}));y.dispatchEvent(new Event('input',{bubbles:true}))}}
function overlay(){let o=$('#firstRunOverlay');if(!o){o=document.createElement('div');o.id='firstRunOverlay';o.className='first-run-overlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');o.innerHTML='<div class="first-run-card" id="firstRunCard"></div>';document.body.appendChild(o)}return o}
function show(on=true){overlay().classList.toggle('show',on);document.documentElement.classList.toggle('setup-open',on)}
const dots=n=>`<div class="setup-progress"><span class="${n>=1?'active':''}">1</span><i></i><span class="${n>=2?'active':''}">2</span><i></i><span class="${n>=3?'active':''}">3</span></div>`;
function checks(){const m=mode(),voice=voiceNow();return `<div class="setup-checklist"><div class="${calOK()?'done':''}"><span>${calOK()?'✓':'1'}</span><p><b>Caméra calibrée</b><small>${calOK()?'Calibration enregistrée.':'Lance la calibration des yeux pendant 3 secondes.'}</small></p></div><div class="${detOK()?'done':''}"><span>${detOK()?'✓':'2'}</span><p><b>Détection réglée</b><small>Fermeture des yeux et sensibilité du bâillement.</small></p></div><div class="${volOK()?'done':''}"><span>${volOK()?'✓':'3'}</span><p><b>Volume confirmé</b><small>Choisis un niveau d’alarme audible.</small></p></div><div class="optional ${voice?'done':''}"><span>${voice?'✓':'○'}</span><p><b>Voix personnelle · facultatif</b><small>${m==='siren'?'La sirène est sélectionnée.':voice?'Message vocal prêt pour cette session.':'Enregistre puis écoute ton message si tu utilises le mode voix.'}</small></p></div></div>`}
function installStep(msg=''){const s=load(),ok=installed()||s.installDone;show();$('#firstRunCard').innerHTML=`${dots(1)}<div class="setup-kicker">PREMIÈRE MISE EN ROUTE</div><h2 id="firstRunTitle">Préparons VIGILANCE</h2><p class="setup-lead">L’installation et quelques réglages essentiels permettent un démarrage fiable avant le premier trajet.</p><div class="setup-focus ${ok?'ok':''}"><span class="setup-focus-icon">${ok?'✓':'↓'}</span><div><b>${ok?'Application installée':'Installer l’application'}</b><small>${ok?'VIGILANCE fonctionne en mode application.':'Installation recommandée pour un accès rapide depuis le téléphone.'}</small></div></div>${msg?`<div class="setup-message">${msg}</div>`:''}<div class="setup-actions"><button id="setupInstallAction" class="setup-primary">${ok?'CONTINUER':promptEvent?'INSTALLER VIGILANCE':'VÉRIFIER L’INSTALLATION'}</button>${!ok&&!promptEvent?'<button id="setupInstallSkip" class="setup-secondary">CONFIGURER MAINTENANT</button>':''}</div>${!ok&&!promptEvent?'<p class="setup-help">Si Chrome ne propose pas encore l’installation, utilise le menu ⋮ puis « Installer l’application » ou « Ajouter à l’écran d’accueil ».</p>':''}`;
$('#setupInstallAction').onclick=async()=>{if(ok){save({installDone:true,stage:'settings'});settingsStep();return}if(promptEvent){try{await promptEvent.prompt();const r=await promptEvent.userChoice;if(r?.outcome==='accepted'){save({installDone:true,installSkipped:false,stage:'settings'});promptEvent=null;settingsStep('Installation validée. Passons aux réglages.')}else installStep('Installation annulée. Tu peux la relancer quand tu veux.')}catch{installStep('La fenêtre automatique n’est pas disponible. Utilise le menu du navigateur.')}}else if(installed()){save({installDone:true,stage:'settings'});settingsStep()}else installStep('Aucune fenêtre automatique n’est disponible pour le moment.')};
$('#setupInstallSkip')?.addEventListener('click',()=>{save({installSkipped:true,stage:'settings'});settingsStep('Tu peux terminer les réglages maintenant et installer l’application ensuite.')})}
function settingsStep(msg=''){save({stage:'settings',installDone:installed()||load().installDone});show();$('#firstRunCard').innerHTML=`${dots(2)}<div class="setup-kicker">CONFIGURATION ESSENTIELLE</div><h2 id="firstRunTitle">Réglons VIGILANCE</h2><p class="setup-lead">Ouvre les paramètres, calibre la caméra puis confirme la détection et le volume.</p>${msg?`<div class="setup-message ok">${msg}</div>`:''}${checks()}<div class="setup-actions"><button id="setupOpenSettings" class="setup-primary">OUVRIR LES PARAMÈTRES</button><button id="setupCheckNow" class="setup-secondary">VÉRIFIER MAINTENANT</button></div>`;$('#setupOpenSettings').onclick=openSettings;$('#setupCheckNow').onclick=()=>configOK()?verifyStep():settingsStep('Il reste au moins un réglage obligatoire à terminer.')}
function dock(){let d=$('#setupDock');if(!d){d=document.createElement('aside');d.id='setupDock';d.className='setup-dock';document.body.appendChild(d)}const ok=configOK();d.innerHTML=`<div class="setup-dock-head"><div><small>PREMIÈRE CONFIGURATION</small><b>${ok?'Réglages essentiels prêts':'Termine les réglages essentiels'}</b></div><span>${ok?'✓':'…'}</span></div>${checks()}<div class="setup-dock-actions"><button id="setupSaveCurrent" class="setup-secondary">VALIDER LES RÉGLAGES AFFICHÉS</button><button id="setupFinishSettings" class="setup-primary" ${ok?'':'disabled'}>TERMINER LA CONFIGURATION</button></div>`;d.classList.add('show');$('#setupSaveCurrent').onclick=()=>{persistCurrent();dock()};$('#setupFinishSettings').onclick=()=>{persistCurrent();if(configOK()){d.classList.remove('show');verifyStep()}else dock()};return d}
function openSettings(){show(false);$('#settingsBtn')?.click();dock();clearInterval(timer);timer=setInterval(()=>{if(!load().completed&&!$('#settingsView')?.hidden)dock();else clearInterval(timer)},1500)}
function verifyStep(){persistCurrent();if(!configOK()){settingsStep('La vérification a détecté un réglage manquant.');return}const s=load();show();$('#firstRunCard').innerHTML=`${dots(3)}<div class="setup-kicker">VÉRIFICATION FINALE</div><h2 id="firstRunTitle">VIGILANCE est prête</h2><p class="setup-lead">Les réglages essentiels sont enregistrés sur cet appareil. Aux prochains démarrages, l’accueil s’ouvrira directement tant que la configuration reste valide.</p><div class="setup-summary"><div><span>Installation</span><b>${installed()||s.installDone?'✓ Installée':'◌ Navigateur'}</b></div><div><span>Caméra</span><b>✓ Calibrée</b></div><div><span>Détection</span><b>✓ Réglée</b></div><div><span>Volume</span><b>✓ ${Math.round(+localStorage.getItem(K.vol)*100)} %</b></div></div><div class="setup-actions"><button id="setupComplete" class="setup-primary">ACCÉDER À L’ACCUEIL</button></div><p class="setup-help">Avant chaque trajet, garde le téléphone correctement positionné face au conducteur. VIGILANCE reste une aide et ne remplace jamais le repos.</p>`;$('#setupComplete').onclick=()=>{save({completed:true,stage:'done',installDone:installed()||s.installDone,completedAt:new Date().toISOString()});$('#setupDock')?.classList.remove('show');show(false);$('#backBtn')?.click();statusPanel()}}
function injectPanel(){if($('#setupSystemPanel'))return;const host=$('.settings-sections');if(!host)return;const sec=document.createElement('section');sec.id='setupSystemPanel';sec.className='settings-section glass wide-section setup-system-panel';host.appendChild(sec);statusPanel()}
function statusPanel(){const sec=$('#setupSystemPanel');if(!sec)return;const s=load(),ok=ready(s);sec.innerHTML=`<div class="section-heading"><span class="section-icon">✓</span><div><span class="eyebrow">MISE EN ROUTE</span><h3>État de configuration</h3></div></div><div class="setup-status-grid"><div><span>Application</span><b>${installed()||s.installDone?'✓ Installée':s.installSkipped?'◌ Navigateur':'À installer'}</b></div><div><span>Caméra</span><b>${calOK()?'✓ Calibrée':'À calibrer'}</b></div><div><span>Détection</span><b>${detOK()?'✓ Réglée':'À régler'}</b></div><div><span>Volume</span><b>${volOK()?`✓ ${Math.round(+localStorage.getItem(K.vol)*100)} %`:'À confirmer'}</b></div></div><div class="setup-system-state ${ok?'ok':'warn'}">${ok?'✓ VIGILANCE EST PRÊTE À FONCTIONNER':'⚠ CONFIGURATION À TERMINER'}</div><button id="restartSetupBtn" class="btn secondary">REFAIRE LA CONFIGURATION INITIALE</button>`;$('#restartSetupBtn').onclick=()=>{save({completed:false,stage:installed()?'settings':'install',installDone:installed()||s.installDone,completedAt:null});installed()?settingsStep():installStep()}}
function boot(){injectPanel();if(installed()&&!load().installDone)save({installDone:true});if(ready()){show(false);statusPanel();return}const s=load();!installOK(s)&&s.stage==='install'?installStep():settingsStep()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;if(!load().completed&&load().stage==='install')installStep()});window.addEventListener('appinstalled',()=>{promptEvent=null;save({installDone:true,installSkipped:false,stage:'settings'});if(!load().completed)settingsStep('Installation terminée avec succès.');statusPanel()});
document.addEventListener('input',e=>{if(e.target?.matches?.('#alarmVolume,#closureDelay,#yawnThreshold,input[name="alarmMode"]'))setTimeout(()=>{$('#setupDock')?.classList.contains('show')&&dock();statusPanel()},30)});$('#calibrateBtn')?.addEventListener('click',()=>{const w=setInterval(()=>{if(calOK()){clearInterval(w);$('#setupDock')?.classList.contains('show')&&dock();statusPanel()}},500);setTimeout(()=>clearInterval(w),15000)});$('#recordBtn')?.addEventListener('click',()=>setTimeout(()=>$('#setupDock')?.classList.contains('show')&&dock(),5600));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();