(() => {
  const $ = s => document.querySelector(s);
  const els = {
    banner: $('#recommendationBanner'), icon: $('#recommendationIcon'), level: $('#recommendationLevel'),
    title: $('#recommendationTitle'), text: $('#recommendationText'), startBreak: $('#startBreakBtn'),
    dismiss: $('#dismissRecommendationBtn'), breakPanel: $('#breakPanel'), breakCountdown: $('#breakCountdown'),
    endBreak: $('#endBreakBtn'), voice: $('#recommendationVoice'), vigilance: $('#vigilanceLevel'),
    perclos: $('#perclos'), yawns: $('#yawnCount'), startBtn: $('#startBtn'), stopBtn: $('#stopBtn'),
    riskOverlay: $('#riskOverlay'), alarmVolume: $('#alarmVolume')
  };
  if (!els.banner || !els.dismiss || !els.vigilance) return;

  const VOICE_KEY='cr3atix-vigilance-recommendation-voice-v1';
  const TRIP_KEY='cr3atix-vigilance-trip-v172';
  const RECS={
    plan90:{severity:'info',icon:'🕒',level:'PRÉVENTION',title:'PRÉVOYEZ UNE PAUSE',text:'Le temps de conduite cumulé approche de 2 heures. Prévoyez un arrêt dans les 30 prochaines minutes, même si la vigilance reste bonne.',voice:'Le temps de conduite approche de deux heures. Prévoyez une pause dans les trente prochaines minutes.',break:false,cooldown:Infinity},
    break120:{severity:'warn',icon:'☕',level:'PAUSE RECOMMANDÉE',title:'IL EST TEMPS DE FAIRE UNE PAUSE',text:'Environ 2 heures de conduite cumulée se sont écoulées. Arrêtez-vous dans un endroit sûr pendant 15 à 20 minutes avant de poursuivre.',voice:'Environ deux heures de conduite se sont écoulées. Une pause de quinze à vingt minutes est recommandée dans un endroit sûr.',break:true,cooldown:30*60*1000},
    yawns:{severity:'warn',icon:'🥱',level:'SIGNES DE FATIGUE',title:'DES BÂILLEMENTS SE RÉPÈTENT',text:'Plusieurs bâillements ont été détectés récemment. Prévoyez un arrêt prochainement. Hydratez-vous, marchez un peu et reposez-vous. Un café peut aider temporairement mais ne remplace pas le repos.',voice:'Plusieurs bâillements ont été détectés récemment. Prévoyez un arrêt prochainement et reposez-vous. Le café ne remplace pas le repos.',break:true,cooldown:15*60*1000},
    repeated:{severity:'warn',icon:'⚠',level:'VIGILANCE EN BAISSE',title:'LES SIGNES DE FATIGUE SE RÉPÈTENT',text:'Plusieurs épisodes distincts de baisse de vigilance ont été détectés récemment. Arrêtez-vous au prochain endroit sécurisé et reposez-vous avant de continuer.',voice:'Les signes de fatigue se répètent. Arrêtez-vous au prochain endroit sécurisé et reposez-vous avant de continuer.',break:true,cooldown:10*60*1000},
    highFatigue:{severity:'danger',icon:'🛑',level:'FATIGUE ÉLEVÉE',title:'UNE PAUSE EST NÉCESSAIRE',text:'La vigilance est fortement dégradée. Arrêtez-vous dès que possible en sécurité. Une sieste de 15 à 20 minutes est recommandée si la somnolence persiste.',voice:'La vigilance est fortement dégradée. Arrêtez-vous dès que possible en sécurité et reposez-vous. Une sieste courte est recommandée si la somnolence persiste.',break:true,cooldown:8*60*1000},
    danger:{severity:'danger',icon:'🛑',level:'SOMNOLENCE DÉTECTÉE',title:'ARRÊTEZ-VOUS DÈS QUE POSSIBLE',text:'Ne poursuivez pas le trajet tant que la somnolence persiste. Rejoignez un endroit sûr, reposez-vous et envisagez une sieste de 15 à 20 minutes avant de reprendre.',voice:'Somnolence détectée. Arrêtez-vous dès que possible dans un endroit sûr. Ne poursuivez pas le trajet tant que la somnolence persiste.',break:true,cooldown:5*60*1000}
  };
  const rank={info:1,warn:2,danger:3};
  const state={running:false,lastLabel:'EN VEILLE',fatigueEvents:[],fatigueEpisodeActive:false,greenSince:0,yawnEvents:[],lastYawnCount:0,active:null,dismissed:new Map(),breakActive:false,breakEndsAt:0,breakTimer:null,voiceEnabled:true,tripMs:0,lastTickEpoch:Date.now(),lastTripPersistAt:0,stoppedAt:0};

  function alarmActive(){return Boolean(els.riskOverlay?.classList.contains('show'));}
  function volume(){return Math.max(0,Math.min(1,Number(els.alarmVolume?.value??85)/100));}
  function speak(text){if(!state.voiceEnabled||alarmActive()||!text||!('speechSynthesis' in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.96;u.pitch=1;u.volume=volume();speechSynthesis.speak(u);}catch{}}
  function loadTrip(){try{const saved=JSON.parse(localStorage.getItem(TRIP_KEY)||'null');if(saved&&Number.isFinite(saved.ms)&&Number.isFinite(saved.lastSeen)&&Date.now()-saved.lastSeen<20*60*1000)state.tripMs=Math.max(0,saved.ms);}catch{}}
  function saveTrip(){localStorage.setItem(TRIP_KEY,JSON.stringify({ms:Math.max(0,state.tripMs),lastSeen:Date.now()}));state.lastTripPersistAt=Date.now();}
  function resetTrip(){state.tripMs=0;state.lastTickEpoch=Date.now();saveTrip();}
  function updateTrip(running){const now=Date.now(),delta=Math.max(0,Math.min(2500,now-state.lastTickEpoch));state.lastTickEpoch=now;if(running){state.tripMs+=delta;if(now-state.lastTripPersistAt>=10000)saveTrip();}else if(state.stoppedAt&&now-state.stoppedAt>=20*60*1000&&state.tripMs>0)resetTrip();}
  function hideRecommendation(cancelSpeech=true){state.active=null;els.banner.hidden=true;if(cancelSpeech&&'speechSynthesis'in window)try{speechSynthesis.cancel()}catch{}}
  function showRecommendation(id){const rec=RECS[id];if(!rec||state.breakActive||alarmActive())return;const now=Date.now(),until=state.dismissed.get(id)||0;if(until>now)return;if(state.active){if(state.active.id===id)return;const cur=RECS[state.active.id];if(cur&&rank[cur.severity]>rank[rec.severity])return;}state.active={id,shownAt:now};els.banner.className=`recommendation-banner ${rec.severity}`;els.icon.textContent=rec.icon;els.level.textContent=rec.level;els.title.textContent=rec.title;els.text.textContent=rec.text;els.startBreak.hidden=!rec.break;els.banner.hidden=false;speak(rec.voice);}
  function dismissRecommendation(){if(!state.active)return;const rec=RECS[state.active.id],now=Date.now(),cooldown=rec?.cooldown??10*60*1000;state.dismissed.set(state.active.id,cooldown===Infinity?Infinity:now+cooldown);hideRecommendation(true);}
  function updateFatigueEpisodes(label,now){const fatigue=['ATTENTION','DANGER','FATIGUE ÉLEVÉE'].includes(label);if(fatigue){state.greenSince=0;if(!state.fatigueEpisodeActive){state.fatigueEpisodeActive=true;state.fatigueEvents.push(now);}}else if(label==='VIGILANT'&&state.fatigueEpisodeActive){if(!state.greenSince)state.greenSince=now;if(now-state.greenSince>=10000){state.fatigueEpisodeActive=false;state.greenSince=0;}}state.fatigueEvents=state.fatigueEvents.filter(t=>now-t<=10*60*1000);}
  function updateYawns(now){const count=Number(els.yawns?.textContent)||0;if(count>state.lastYawnCount){for(let i=state.lastYawnCount;i<count;i++)state.yawnEvents.push(now);}state.lastYawnCount=count;state.yawnEvents=state.yawnEvents.filter(t=>now-t<=10*60*1000);}
  function checkRecommendations(){if(!state.running||state.breakActive||alarmActive()){if(alarmActive())hideRecommendation(true);return;}const label=(els.vigilance?.textContent||'').trim();const p=Number(els.perclos?.textContent)||0;let candidate=null;if(label==='DANGER')candidate='danger';else if(label==='FATIGUE ÉLEVÉE'||p>=35)candidate='highFatigue';else if(state.fatigueEvents.length>=3)candidate='repeated';else if(state.yawnEvents.length>=2)candidate='yawns';else if(state.tripMs>=120*60*1000)candidate='break120';else if(state.tripMs>=90*60*1000)candidate='plan90';if(candidate)showRecommendation(candidate);}
  function formatBreak(ms){const t=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(t/60),s=t%60;return `${m}:${String(s).padStart(2,'0')}`;}
  function updateBreak(){if(!state.breakActive)return;const remaining=state.breakEndsAt-Date.now();els.breakCountdown.textContent=formatBreak(remaining);if(remaining<=0)endBreak(true);}
  function startBreak(){if(state.breakActive)return;if(!confirm('Activez la pause uniquement une fois le véhicule stationné dans un endroit sûr. Confirmer que le véhicule est arrêté ?'))return;if(state.running&&!els.stopBtn.disabled)els.stopBtn.click();hideRecommendation(true);state.breakActive=true;state.breakEndsAt=Date.now()+15*60*1000;els.breakPanel.hidden=false;updateBreak();state.breakTimer=setInterval(updateBreak,1000);speak('Pause de quinze minutes démarrée. Reposez-vous et ne reprenez la route que si vous vous sentez pleinement réveillé et vigilant.');}
  function endBreak(completed=false){if(!state.breakActive)return;state.breakActive=false;if(state.breakTimer)clearInterval(state.breakTimer);state.breakTimer=null;state.breakEndsAt=0;els.breakPanel.hidden=true;state.fatigueEvents=[];state.yawnEvents=[];state.fatigueEpisodeActive=false;state.greenSince=0;state.dismissed.clear();if(completed){resetTrip();speak("La pause de quinze minutes est terminée. Avant de reprendre la route, assurez-vous d'être pleinement réveillé et vigilant.");}}
  function resetSessionSignals(){state.fatigueEvents=[];state.yawnEvents=[];state.lastYawnCount=Number(els.yawns?.textContent)||0;state.fatigueEpisodeActive=false;state.greenSince=0;state.dismissed.clear();hideRecommendation(true);}
  function updateVoiceSetting(){state.voiceEnabled=els.voice?.checked!==false;localStorage.setItem(VOICE_KEY,state.voiceEnabled?'1':'0');if(!state.voiceEnabled&&'speechSynthesis'in window)try{speechSynthesis.cancel()}catch{}}

  loadTrip();const stored=localStorage.getItem(VOICE_KEY);state.voiceEnabled=stored===null?true:stored==='1';if(els.voice)els.voice.checked=state.voiceEnabled;
  els.dismiss.addEventListener('click',dismissRecommendation);els.startBreak.addEventListener('click',startBreak);els.endBreak.addEventListener('click',()=>endBreak(false));els.voice?.addEventListener('change',updateVoiceSetting);els.startBtn?.addEventListener('click',()=>{if(state.breakActive)endBreak(false);});window.addEventListener('beforeunload',saveTrip);

  setInterval(()=>{const now=Date.now();const running=Boolean(els.startBtn?.disabled&&!els.stopBtn?.disabled);updateTrip(running);if(running&&!state.running){state.running=true;state.stoppedAt=0;state.lastLabel='EN VEILLE';resetSessionSignals();}if(!running&&state.running){state.running=false;state.stoppedAt=now;hideRecommendation(true);saveTrip();}if(!state.running||state.breakActive)return;if(alarmActive()){hideRecommendation(true);return;}const label=(els.vigilance?.textContent||'').trim();updateFatigueEpisodes(label,now);updateYawns(now);state.lastLabel=label;checkRecommendations();},1000);
})();
