import fs from 'node:fs';
const fail=m=>{console.error('VERIFY FAIL:',m);process.exit(1)};
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const app=read('app.js');
const core=read('app-core-v16.js');
const rec=read('recommendations-v17.js');
const runtime=read('runtime-v18.js');
const runtimeCss=read('runtime-v18.css');
const onboard=read('onboarding-v19.js');
const onboardCss=read('onboarding-v19.css');
const sw=read('sw.js');
for(const typo of ['Tèsd','Bâuil','VISGCE','IGNORER LA RECOMMANDATION']) if(index.includes(typo)) fail(`texte incorrect: ${typo}`);
for(const id of ['camera','startBtn','stopBtn','ignoreAlertBtn','recommendationBanner','dismissRecommendationBtn','startBreakBtn','calibrateBtn','perclos','yawnCount']) if(!index.includes(`id="${id}"`)) fail(`id manquant: ${id}`);
for(const token of ['calculatePerclos','delegate:"CPU"','alarmSnoozeUntil','yawnStartedAt','DETECTION_SETTINGS_KEY']) if(!core.includes(token)) fail(`stabilisation absente: ${token}`);
for(const token of ['TRIP_KEY','fatigueEpisodeActive','yawnEvents','alarmActive()){hideRecommendation']) if(!rec.includes(token)) fail(`recommandations incomplètes: ${token}`);
for(const token of ['./runtime-v18.js','./runtime-v18.css','./onboarding-v19.js','./onboarding-v19.css']) if(!app.includes(token)) fail(`module non chargé: ${token}`);
for(const token of ['navigator.wakeLock.request','visibilitychange','resumeAfterBackground','restartMonitoring']) if(!runtime.includes(token)) fail(`runtime incomplet: ${token}`);
for(const token of ['cr3atix-vigilance-setup-v19','beforeinstallprompt','appinstalled','configOK','REFAIRE LA CONFIGURATION INITIALE','VALIDER LES RÉGLAGES AFFICHÉS']) if(!onboard.includes(token)) fail(`onboarding incomplet: ${token}`);
if(!onboardCss.includes('.first-run-overlay')||!onboardCss.includes('.setup-dock')) fail('styles onboarding incomplets');
if(!sw.includes('cr3atix-vigilance-v1.9')) fail('cache V1.9 absent');
for(const asset of ['runtime-v18.js','runtime-v18.css','onboarding-v19.js','onboarding-v19.css']) if(!sw.includes(asset)) fail(`asset absent du cache: ${asset}`);
if(!sw.includes('e.request.mode==="navigate"')) fail('fallback service worker trop large');
console.log('V1.9 verification OK');
