import fs from 'node:fs';
const fail=m=>{console.error('VERIFY FAIL:',m);process.exit(1)};
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const app=read('app.js');
const core=read('app-core-v16.js');
const rec=read('recommendations-v17.js');
const runtime=read('runtime-v18.js');
const onboard=read('onboarding-v200.js');
const onboardCss=read('onboarding-v20.css');
const sw=read('sw.js');
const manifest=JSON.parse(read('manifest.webmanifest'));
for(const typo of ['Tèsd','Bâuil','VISGCE','IGNORER LA RECOMMANDATION']) if(index.includes(typo)) fail(`texte incorrect: ${typo}`);
for(const id of ['camera','startBtn','stopBtn','ignoreAlertBtn','recommendationBanner','dismissRecommendationBtn','startBreakBtn','calibrateBtn','closureDelay','yawnThreshold','alarmVolume','recordBtn']) if(!index.includes(`id="${id}"`)) fail(`id manquant: ${id}`);
for(const token of ['calculatePerclos','delegate:"CPU"','alarmSnoozeUntil','yawnStartedAt','DETECTION_SETTINGS_KEY']) if(!core.includes(token)) fail(`stabilisation absente: ${token}`);
for(const token of ['TRIP_KEY','fatigueEpisodeActive','yawnEvents','alarmActive()){hideRecommendation']) if(!rec.includes(token)) fail(`recommandations incomplètes: ${token}`);
for(const token of ['./runtime-v18.js','./runtime-v18.css','./onboarding-v200.js','./onboarding-v20.css']) if(!app.includes(token)) fail(`module non chargé: ${token}`);
for(const forbidden of ['./onboarding-v19.js','./onboarding-mandatory-v193.js','./onboarding-v194.js','./onboarding-v195.js','./onboarding-v196.js','./onboarding-v197.js','./onboarding-v198.js','./onboarding-v19.css']) if(app.includes(forbidden)) fail(`ancien onboarding encore chargé: ${forbidden}`);
for(const token of ['navigator.wakeLock.request','visibilitychange','resumeAfterBackground','restartMonitoring']) if(!runtime.includes(token)) fail(`runtime incomplet: ${token}`);
for(const token of ['cr3atix-vigilance-setup-v200','const VERSION = 200','beforeinstallprompt','appinstalled','getInstalledRelatedApps','detectInstalledApp','renderInstallStep','renderCalibrationStep','renderDetectionStep','renderAlarmStep','renderFinalStep','wizardCalibrationNext','wizardDetectionNext','wizardAlarmNext','wizardFinish','REFAIRE L’ASSISTANT DE CONFIGURATION','mountSection','restoreAll']) if(!onboard.includes(token)) fail(`assistant V2 incomplet: ${token}`);
if(onboard.includes('CONFIRMER DÉTECTION ET VOLUME')) fail('ancienne validation groupée encore présente');
if(onboard.includes('setupGuide')) fail('ancien bloc paramètres encore présent');
if(onboard.includes("'(display-mode: fullscreen)'")) fail('fullscreen ne doit pas valider une installation');
for(const token of ['.setup-wizard','position:fixed','100dvh','touch-action:manipulation!important','.setup-wizard-slot','.wizard-summary']) if(!onboardCss.includes(token)) fail(`style assistant V2 absent: ${token}`);
if(manifest.id!=='/CR3ATIX-VIGILANCE/') fail('manifest id incorrect');
if(manifest.scope!=='./') fail('manifest scope manquant');
if(manifest.prefer_related_applications!==false) fail('prefer_related_applications doit rester false');
if(!Array.isArray(manifest.related_applications)||!manifest.related_applications.some(a=>a.platform==='webapp'&&a.url==='./manifest.webmanifest')) fail('auto-référence PWA absente du manifest');
if(!sw.includes('cr3atix-vigilance-v2.0.0')) fail('cache V2.0.0 absent');
for(const asset of ['runtime-v18.js','runtime-v18.css','onboarding-v200.js','onboarding-v20.css','manifest.webmanifest']) if(!sw.includes(asset)) fail(`asset absent du cache: ${asset}`);
for(const old of ['onboarding-v198.js','onboarding-v19.css','onboarding-mandatory-v193.js','onboarding-v194.js','onboarding-v195.js','onboarding-v196.js','onboarding-v197.js']) if(sw.includes(old)) fail(`ancien onboarding encore mis en cache: ${old}`);
for(const token of ['self.clients.claim()','self.clients.matchAll({type:"window"})','client.navigate(client.url)','cache:"no-store"','manifest.webmanifest']) if(!sw.includes(token)) fail(`mise à jour service worker incomplète: ${token}`);
console.log('V2.0.0 verification OK');
