import fs from 'node:fs';
const fail=m=>{console.error('VERIFY FAIL:',m);process.exit(1)};
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const app=read('app.js');
const core=read('app-core-v16.js');
const rec=read('recommendations-v17.js');
const runtime=read('runtime-v18.js');
const onboard=read('onboarding-v195.js');
const onboardCss=read('onboarding-v19.css');
const sw=read('sw.js');
for(const typo of ['Tèsd','Bâuil','VISGCE','IGNORER LA RECOMMANDATION']) if(index.includes(typo)) fail(`texte incorrect: ${typo}`);
for(const id of ['camera','startBtn','stopBtn','ignoreAlertBtn','recommendationBanner','dismissRecommendationBtn','startBreakBtn','calibrateBtn','perclos','yawnCount']) if(!index.includes(`id="${id}"`)) fail(`id manquant: ${id}`);
for(const token of ['calculatePerclos','delegate:"CPU"','alarmSnoozeUntil','yawnStartedAt','DETECTION_SETTINGS_KEY']) if(!core.includes(token)) fail(`stabilisation absente: ${token}`);
for(const token of ['TRIP_KEY','fatigueEpisodeActive','yawnEvents','alarmActive()){hideRecommendation']) if(!rec.includes(token)) fail(`recommandations incomplètes: ${token}`);
for(const token of ['./runtime-v18.js','./runtime-v18.css','./onboarding-v195.js']) if(!app.includes(token)) fail(`module non chargé: ${token}`);
for(const forbidden of ['./onboarding-v19.js','./onboarding-mandatory-v193.js','./onboarding-v194.js']) if(app.includes(forbidden)) fail(`ancien onboarding encore chargé: ${forbidden}`);
for(const token of ['navigator.wakeLock.request','visibilitychange','resumeAfterBackground','restartMonitoring']) if(!runtime.includes(token)) fail(`runtime incomplet: ${token}`);
for(const token of ['cr3atix-vigilance-setup-v195','const VERSION = 195','beforeinstallprompt','appinstalled','isInstalled()','renderInstall','beginConfiguration','setupConfigOK','calibrationConfirmed','detectionConfirmed','volumeConfirmed','REFAIRE LA CONFIGURATION INITIALE','Installation requise','showSettingsView']) if(!onboard.includes(token)) fail(`onboarding V1.9.5 incomplet: ${token}`);
if(onboard.includes('CONFIGURER MAINTENANT')) fail('un contournement de l’installation est encore présent');
if(onboard.includes("'(display-mode: fullscreen)'")) fail('fullscreen ne doit pas valider une installation');
if(!onboard.includes('beginConfiguration();')) fail('la configuration installée doit ouvrir automatiquement les paramètres');
if(!onboard.includes('after !== before && calOK()')) fail('la calibration doit être refaite pendant la session de configuration');
if(!onboardCss.includes('background:var(--surface,#fff)')) fail('la fenêtre onboarding doit suivre le thème et rester lisible');
if(!onboardCss.includes('pointer-events:auto')) fail('les contrôles onboarding doivent accepter les interactions tactiles');
if(!sw.includes('cr3atix-vigilance-v1.9.5')) fail('cache V1.9.5 absent');
for(const asset of ['runtime-v18.js','runtime-v18.css','onboarding-v195.js','onboarding-v19.css']) if(!sw.includes(asset)) fail(`asset absent du cache: ${asset}`);
if(sw.includes('onboarding-mandatory-v193.js')||sw.includes('onboarding-v194.js')) fail('ancien onboarding encore mis en cache');
for(const token of ['self.clients.claim()','self.clients.matchAll({type:"window"})','client.navigate(client.url)','cache:"no-store"']) if(!sw.includes(token)) fail(`mise à jour service worker incomplète: ${token}`);
console.log('V1.9.5 verification OK');
