import fs from 'node:fs';
const fail=m=>{console.error('VERIFY FAIL:',m);process.exit(1)};
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const app=read('app.js');
const core=read('app-core-v16.js');
const rec=read('recommendations-v17.js');
const runtime=read('runtime-v18.js');
const onboard=read('onboarding-v197.js');
const onboardCss=read('onboarding-v19.css');
const sw=read('sw.js');
for(const typo of ['Tèsd','Bâuil','VISGCE','IGNORER LA RECOMMANDATION']) if(index.includes(typo)) fail(`texte incorrect: ${typo}`);
for(const id of ['camera','startBtn','stopBtn','ignoreAlertBtn','recommendationBanner','dismissRecommendationBtn','startBreakBtn','calibrateBtn','perclos','yawnCount']) if(!index.includes(`id="${id}"`)) fail(`id manquant: ${id}`);
for(const token of ['calculatePerclos','delegate:"CPU"','alarmSnoozeUntil','yawnStartedAt','DETECTION_SETTINGS_KEY']) if(!core.includes(token)) fail(`stabilisation absente: ${token}`);
for(const token of ['TRIP_KEY','fatigueEpisodeActive','yawnEvents','alarmActive()){hideRecommendation']) if(!rec.includes(token)) fail(`recommandations incomplètes: ${token}`);
for(const token of ['./runtime-v18.js','./runtime-v18.css','./onboarding-v197.js']) if(!app.includes(token)) fail(`module non chargé: ${token}`);
for(const forbidden of ['./onboarding-v19.js','./onboarding-mandatory-v193.js','./onboarding-v194.js','./onboarding-v195.js','./onboarding-v196.js']) if(app.includes(forbidden)) fail(`ancien onboarding encore chargé: ${forbidden}`);
for(const token of ['navigator.wakeLock.request','visibilitychange','resumeAfterBackground','restartMonitoring']) if(!runtime.includes(token)) fail(`runtime incomplet: ${token}`);
for(const token of ['cr3atix-vigilance-setup-v197','const VERSION = 197','beforeinstallprompt','appinstalled','isInstalled()','renderInstall','beginConfiguration','setupConfigOK','calibrationConfirmed','detectionConfirmed','volumeConfirmed','REFAIRE LA CONFIGURATION INITIALE','Installation requise','setupGuide']) if(!onboard.includes(token)) fail(`onboarding V1.9.7 incomplet: ${token}`);
if(onboard.includes('CONFIGURER MAINTENANT')) fail('un contournement de l’installation est encore présent');
if(onboard.includes("'(display-mode: fullscreen)'")) fail('fullscreen ne doit pas valider une installation');
if(onboard.includes('setup-dock')) fail('le panneau flottant bloquant ne doit plus exister');
if(!onboard.includes('after!==before && calOK()')) fail('la calibration doit être refaite pendant la session de configuration');
if(!onboard.includes("addEventListener('click',completeConfiguration,{once:true})")) fail('le bouton terminer doit avoir un gestionnaire unique');
for(const token of ['.setup-guide','pointer-events:auto!important','touch-action:manipulation!important']) if(!onboardCss.includes(token)) fail(`protection tactile absente: ${token}`);
if(onboardCss.includes('.setup-dock')) fail('anciens styles du panneau flottant encore présents');
if(!sw.includes('cr3atix-vigilance-v1.9.7')) fail('cache V1.9.7 absent');
for(const asset of ['runtime-v18.js','runtime-v18.css','onboarding-v197.js','onboarding-v19.css']) if(!sw.includes(asset)) fail(`asset absent du cache: ${asset}`);
for(const old of ['onboarding-mandatory-v193.js','onboarding-v194.js','onboarding-v195.js','onboarding-v196.js']) if(sw.includes(old)) fail(`ancien onboarding encore mis en cache: ${old}`);
for(const token of ['self.clients.claim()','self.clients.matchAll({type:"window"})','client.navigate(client.url)','cache:"no-store"']) if(!sw.includes(token)) fail(`mise à jour service worker incomplète: ${token}`);
console.log('V1.9.7 verification OK');
